# Generated by Django 4.1.3 on 2023-01-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
    ]
